---

- name: Install dependencies
  apt:
    pkg:
    - software-properties-common
    - apt-transport-https
    - ca-certificates

- name: Add an Apt signing key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
- apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present

- name: Install Sublime text
  apt:
    pkg:
    - sublime-text

- name: Bash aliases | Add aliases
  lineinfile:
    dest: "{{ bash_aliases_path }}"
    create: yes
    mode: 0644
    line: 'alias sublime="/opt/sublime_text/sublime_text %F"'

 

